[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
startCommand = "uvicorn app:app --host 0.0.0.0 --port $PORT"

[env]
PORT = "8000"
